import * as images from "../assets";
const products = [
  // Sugar
  {
    name: "Sugar S1-30",
    image: images.sugar,
    vegTag: images.vegTag,
    isVeg: true,
    mrp: 45,
    price: 30,
    discount: 15,
    quantities: ["1 kg (₹0.30 / 1 gm)", "5 kg (₹0.28 / 1 gm)"],
  },
  {
    name: "Sugar S2-30",
    image: images.sugar,
    vegTag: images.vegTag,
    isVeg: true,
    mrp: 50,
    price: 30,
    discount: 20,
    quantities: ["1 kg (₹0.30 / 1 gm)", "5 kg (₹0.28 / 1 gm)"],
  },
  {
    name: "Sugar M30",
    image: images.sugar,
    vegTag: images.vegTag,
    isVeg: true,
    mrp: 55,
    price: 35,
    discount: 20,
    quantities: ["1 kg (₹0.35 / 1 gm)", "5 kg (₹0.33 / 1 gm)"],
  },

  // Rice (All Varieties)
  {
    name: "Rice Ponni",
    image: images.rice,
    vegTag: images.vegTag,
    isVeg: true,
    mrp: 60,
    price: 50,
    discount: 10,
    quantities: ["1 kg (₹0.50 / 1 gm)", "10 kg (₹0.48 / 1 gm)"],
  },
  {
    name: "Rice Basmati",
    image: images.rice,
    vegTag: images.vegTag,
    isVeg: true,
    mrp: 120,
    price: 100,
    discount: 20,
    quantities: ["1 kg (₹1.00 / 1 gm)", "5 kg (₹0.95 / 1 gm)"],
  },

  // Oil
  {
    name: "Sunflower Oil",
    image: images.Sunflower,
    vegTag: images.vegTag,
    isVeg: true,
    mrp: 170,
    price: 150,
    discount: 20,
    quantities: ["1 L (₹150/L)", "5 L (₹145/L)"],
  },
  {
    name: "Palmolein Oil",
    image: images.Palmolein,
    vegTag: images.vegTag,
    isVeg: true,
    mrp: 130,
    price: 120,
    discount: 10,
    quantities: ["1 L (₹120/L)", "5 L (₹115/L)"],
  },
  {
    name: "Coconut Oil",
    image: images.Coconut,
    vegTag: images.vegTag,
    isVeg: true,
    mrp: 250,
    price: 230,
    discount: 20,
    quantities: ["1 L (₹230/L)", "5 L (₹225/L)"],
  },
  {
    name: "Gingelly Oil",
    image: images.Gingelly,
    vegTag: images.vegTag,
    isVeg: true,
    mrp: 280,
    price: 260,
    discount: 20,
    quantities: ["1 L (₹260/L)", "5 L (₹255/L)"],
  },

  // Dal
  {
    name: "Toor Dal",
    image: images.Toor,
    vegTag: images.vegTag,
    isVeg: true,
    mrp: 120,
    price: 100,
    discount: 20,
    quantities: ["1 kg (₹100/kg)", "5 kg (₹95/kg)"],
  },
  {
    name: "Urad Dal (Whole)",
    image: images.Urad,
    vegTag: images.vegTag,
    isVeg: true,
    mrp: 150,
    price: 140,
    discount: 10,
    quantities: ["1 kg (₹140/kg)", "5 kg (₹135/kg)"],
  },
  {
    name: "Urad Dal (Broken)",
    image: images.Urad,
    vegTag: images.vegTag,
    isVeg: true,
    mrp: 130,
    price: 120,
    discount: 10,
    quantities: ["1 kg (₹120/kg)", "5 kg (₹115/kg)"],
  },
  {
    name: "Chana Dal",
    image: images.Chana,
    vegTag: images.vegTag,
    isVeg: true,
    mrp: 90,
    price: 80,
    discount: 10,
    quantities: ["1 kg (₹80/kg)", "5 kg (₹78/kg)"],
  },
  {
    name: "Moong Dal",
    image: images.Moong,
    vegTag: images.vegTag,
    isVeg: true,
    mrp: 140,
    price: 125,
    discount: 15,
    quantities: ["1 kg (₹125/kg)", "5 kg (₹120/kg)"],
  },

  // Salt
  {
    name: "Salt Crystal",
    image: images.SaltCrystal,
    vegTag: images.vegTag,
    isVeg: true,
    mrp: 25,
    price: 20,
    discount: 5,
    quantities: ["1 kg (₹20/kg)", "5 kg (₹18/kg)"],
  },
  {
    name: "Salt Powdered",
    image: images.salt,
    vegTag: images.vegTag,
    isVeg: true,
    mrp: 20,
    price: 18,
    discount: 2,
    quantities: ["1 kg (₹18/kg)", "5 kg (₹16/kg)"],
  },
];

export default products;
